services:

  app:
    image: simbase_connector:0.1.0
    container_name: simbase_connector
    env_file:
      - .env
    volumes:
      - ./:/app
      - dev-logs:/logger/logs/
    restart: always
    command: >
      sh -c "/py/bin/python main.py"

volumes:
  dev-logs: