"""Minor change

Revision ID: 02f4eda0821f
Revises: b4133d18848b
Create Date: 2025-02-10 10:26:05.554627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f4eda0821f'
down_revision: Union[str, None] = 'b4133d18848b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'comment',
               existing_type=sa.VARCHAR(length=1023),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('income', 'additional_comment',
               existing_type=sa.VARCHAR(length=1023),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('income_id_sm_key', 'income', type_='unique')
    op.drop_column('income', 'id_sm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('id_sm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('income_id_sm_key', 'income', ['id_sm'])
    op.alter_column('income', 'additional_comment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1023),
               existing_nullable=True)
    op.alter_column('income', 'comment',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1023),
               existing_nullable=True)
    # ### end Alembic commands ###
