"""Made exception field larger

Revision ID: 244bd4732392
Revises: 82aac86ead2c
Create Date: 2025-01-30 15:31:03.911382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244bd4732392'
down_revision: Union[str, None] = '82aac86ead2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sql_errors', 'exception',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=8191),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sql_errors', 'exception',
               existing_type=sa.String(length=8191),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
