"""Fixed bug with relationship

Revision ID: 27d6aedd43f1
Revises: cfb1ba4a290b
Create Date: 2025-02-05 10:44:49.406810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d6aedd43f1'
down_revision: Union[str, None] = 'cfb1ba4a290b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('contract_name', sa.String(length=255), nullable=True))
    op.drop_column('objects', 'contract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('contract', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('objects', 'contract_name')
    # ### end Alembic commands ###
