"""renamed posts.operation_mode column

Revision ID: 2f985d5fe8cf
Revises: be0a141266c2
Create Date: 2025-02-10 12:37:37.668709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f985d5fe8cf'
down_revision: Union[str, None] = 'be0a141266c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('operating_mode', sa.Integer(), nullable=True))
    op.drop_column('posts', 'operation_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('operation_mode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'operating_mode')
    # ### end Alembic commands ###
