"""Create transports

Revision ID: 372c5063c3b1
Revises: a75ec8088ede
Create Date: 2025-02-20 16:02:51.603404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372c5063c3b1'
down_revision: Union[str, None] = 'a75ec8088ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transports', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('transports', sa.Column('transport_quantity', sa.SmallInteger(), nullable=True))
    op.add_column('transports', sa.Column('additional_necessary_transport_quantity', sa.SmallInteger(), nullable=True))
    op.drop_constraint('transports_id_sm_key', 'transports', type_='unique')
    op.drop_column('transports', 'additional_necessary_transport_quant')
    op.drop_column('transports', 'id_sm')
    op.drop_column('transports', 'transport_quant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transports', sa.Column('transport_quant', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('id_sm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transports', sa.Column('additional_necessary_transport_quant', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('transports_id_sm_key', 'transports', ['id_sm'])
    op.drop_column('transports', 'additional_necessary_transport_quantity')
    op.drop_column('transports', 'transport_quantity')
    op.drop_column('transports', 'sm_state')
    # ### end Alembic commands ###
