"""Records table added

Revision ID: 3da8745dacba
Revises: dab40edc9148
Create Date: 2025-01-27 09:22:28.293503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da8745dacba'
down_revision: Union[str, None] = 'dab40edc9148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetched_dates',
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('date_created')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fetched_dates')
    # ### end Alembic commands ###
