"""create weapons_and_special_equipments

Revision ID: 3fbca64d8a92
Revises: 443771c674e1
Create Date: 2025-02-04 17:17:10.535748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbca64d8a92'
down_revision: Union[str, None] = '443771c674e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('customer_id_sm', sa.Integer(), nullable=True),
    sa.Column('post_id_sm', sa.Integer(), nullable=True),
    sa.Column('wearable_radios_quant', sa.SmallInteger(), nullable=True),
    sa.Column('сar_radios_quant', sa.SmallInteger(), nullable=True),
    sa.Column('stationary_radios_quant', sa.SmallInteger(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['post_id_sm'], ['posts.id_sm'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('weapons_and_special_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('customer_id_sm', sa.Integer(), nullable=True),
    sa.Column('post_id_sm', sa.Integer(), nullable=True),
    sa.Column('firearms', sa.SmallInteger(), nullable=True),
    sa.Column('handcuffs', sa.SmallInteger(), nullable=True),
    sa.Column('PR73', sa.SmallInteger(), nullable=True),
    sa.Column('regulatory', sa.SmallInteger(), nullable=True),
    sa.Column('electric_lantern', sa.SmallInteger(), nullable=True),
    sa.Column('headlight_finder', sa.SmallInteger(), nullable=True),
    sa.Column('inspection_mirror', sa.SmallInteger(), nullable=True),
    sa.Column('detectors_and_metal_detectors', sa.SmallInteger(), nullable=True),
    sa.Column('binoculars', sa.SmallInteger(), nullable=True),
    sa.Column('safe_for_storing_weapons', sa.SmallInteger(), nullable=True),
    sa.Column('wearable_video_recorders', sa.SmallInteger(), nullable=True),
    sa.Column('car_DVRs', sa.SmallInteger(), nullable=True),
    sa.Column('cell_phones', sa.SmallInteger(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['post_id_sm'], ['posts.id_sm'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapons_and_special_equipments')
    op.drop_table('communication_facilities')
    # ### end Alembic commands ###
