"""Added new tables

Revision ID: 59af41a69f8b
Revises: d1ecd499f2eb
Create Date: 2025-01-29 11:36:54.792066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59af41a69f8b'
down_revision: Union[str, None] = 'd1ecd499f2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetched_dates',
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('date_created')
    )
    op.create_table('mob_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=False),
    sa.Column('customer_id_sm', sa.Integer(), nullable=False),
    sa.Column('object_id_sm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operating_mode', sa.String(length=255), nullable=False),
    sa.Column('linear_part', sa.Text(), nullable=False),
    sa.Column('length_from', sa.Double(), nullable=False),
    sa.Column('length_to', sa.Double(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id_sm'], ['objects.id_sm'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('security_guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('customer_id_sm', sa.Integer(), nullable=True),
    sa.Column('object_id_sm', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('iin', sa.String(length=255), nullable=True),
    sa.Column('social_status', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('employee_photo', sa.LargeBinary(), nullable=True),
    sa.Column('jender', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('labor_union', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id_sm'], ['objects.id_sm'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.alter_column('objects', 'contract',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('objects', 'contract_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'posts', ['id_sm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('objects', 'contract_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('objects', 'contract',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('security_guards')
    op.drop_table('mob_groups')
    op.drop_table('fetched_dates')
    # ### end Alembic commands ###
