"""Added tables

Revision ID: 719ff1ab5b49
Revises: 244bd4732392
Create Date: 2025-01-31 12:11:46.748275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719ff1ab5b49'
down_revision: Union[str, None] = '244bd4732392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('customer_id_sm', sa.Integer(), nullable=True),
    sa.Column('object_id_sm', sa.Integer(), nullable=True),
    sa.Column('contract_id_sm', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=255), nullable=True),
    sa.Column('contract_amount', sa.Double(), nullable=True),
    sa.Column('additional_agreement_amount', sa.Double(), nullable=True),
    sa.Column('amount_avr', sa.Double(), nullable=True),
    sa.Column('payment_date_avr', sa.Date(), nullable=True),
    sa.Column('actual_payment', sa.Double(), nullable=True),
    sa.Column('payment_date_actual', sa.Date(), nullable=True),
    sa.Column('deviation_amount', sa.Double(), nullable=True),
    sa.Column('deviation_from_avr', sa.Double(), nullable=True),
    sa.Column('deviation_from_contract_prc', sa.String(length=255), nullable=True),
    sa.Column('deviation_from_avr_prc', sa.String(length=255), nullable=True),
    sa.Column('remainder', sa.Double(), nullable=True),
    sa.Column('comment', sa.Double(), nullable=True),
    sa.Column('additional_comment', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.add_column('contract', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'name')
    op.drop_table('income')
    # ### end Alembic commands ###
