"""made id_sm nullable

Revision ID: 77665a1e12f4
Revises: 6da32d296632
Create Date: 2025-02-04 08:57:42.295583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77665a1e12f4'
down_revision: Union[str, None] = '6da32d296632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'id_sm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('income_id_sm_key', 'income', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('income_id_sm_key', 'income', ['id_sm'])
    op.alter_column('income', 'id_sm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
