"""Created sql error model

Revision ID: 8f5b5487a6ed
Revises: ce97b91dd68c
Create Date: 2025-01-30 14:08:50.006303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5b5487a6ed'
down_revision: Union[str, None] = 'ce97b91dd68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception', sa.String(length=255), nullable=False),
    sa.Column('traceback', sa.String(length=8191), nullable=False),
    sa.Column('sql', sa.String(length=511), nullable=False),
    sa.Column('source_object', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sql_errors')
    # ### end Alembic commands ###
