"""create incidents

Revision ID: 94810ee5d8e5
Revises: 131bc5ccb4c0
Create Date: 2025-02-04 16:28:07.328274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94810ee5d8e5'
down_revision: Union[str, None] = '131bc5ccb4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('subtype', sa.String(length=255), nullable=True),
    sa.Column('data_on_the_transfer_of_reldata_on_the_transfer_of_relations_applications_to_the_police_departmentations', sa.String(length=255), nullable=True),
    sa.Column('the_case_has_been_transferred_to_the_police', sa.Boolean(), nullable=True),
    sa.Column('the_act_was_submitted_to_the_Security_Council', sa.Boolean(), nullable=True),
    sa.Column('customers_employees', sa.Boolean(), nullable=True),
    sa.Column('KMGSecurity_employees', sa.Boolean(), nullable=True),
    sa.Column('contractor_employees', sa.Boolean(), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('amount_of_damage', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('KMGS_LTD', sa.String(length=255), nullable=True),
    sa.Column('third_party', sa.String(length=255), nullable=True),
    sa.Column('disciplinary', sa.String(length=255), nullable=True),
    sa.Column('KUI', sa.String(length=255), nullable=True),
    sa.Column('ERDR', sa.String(length=255), nullable=True),
    sa.Column('SB', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
