"""Added legal claims

Revision ID: 9e0f48aa7d3e
Revises: dcb95f6ac1f7
Create Date: 2025-02-18 09:19:04.099271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0f48aa7d3e'
down_revision: Union[str, None] = 'dcb95f6ac1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('employee', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('filials', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('fines', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('income', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('objects', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('security_guards', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('shifts', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('triggerings', sa.Column('sm_state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triggerings', 'sm_state')
    op.drop_column('shifts', 'sm_state')
    op.drop_column('security_guards', 'sm_state')
    op.drop_column('posts', 'sm_state')
    op.drop_column('objects', 'sm_state')
    op.drop_column('income', 'sm_state')
    op.drop_column('fines', 'sm_state')
    op.drop_column('filials', 'sm_state')
    op.drop_column('employee', 'sm_state')
    op.drop_column('customers', 'sm_state')
    op.drop_column('contracts', 'sm_state')
    # ### end Alembic commands ###
