"""create shifts

Revision ID: a4ac823965c4
Revises: 94810ee5d8e5
Create Date: 2025-02-04 16:44:58.761287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ac823965c4'
down_revision: Union[str, None] = '94810ee5d8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=True),
    sa.Column('object_id_sm', sa.Integer(), nullable=True),
    sa.Column('post_id_sm', sa.Integer(), nullable=True),
    sa.Column('security_guard_id_sm', sa.Integer(), nullable=True),
    sa.Column('security_guard_replaces_id_sm', sa.Integer(), nullable=True),
    sa.Column('joined_posts', sa.Boolean(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('shift_type', sa.String(length=255), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['object_id_sm'], ['objects.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['post_id_sm'], ['posts.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['security_guard_id_sm'], ['security_guards.id_sm'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['security_guard_replaces_id_sm'], ['security_guards.id_sm'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.add_column('incidents', sa.Column('data_on_the_transfer_of_relations_ap', sa.String(length=255), nullable=True))
    op.drop_column('incidents', 'data_on_the_transfer_of_reldata_on_the_transfer_of_relations_ap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('data_on_the_transfer_of_reldata_on_the_transfer_of_relations_ap', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('incidents', 'data_on_the_transfer_of_relations_ap')
    op.drop_table('shifts')
    # ### end Alembic commands ###
