"""added weapons and special equipments

Revision ID: b1c77b1ce342
Revises: a5e411b24615
Create Date: 2025-02-24 12:50:03.786091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c77b1ce342'
down_revision: Union[str, None] = 'a5e411b24615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons_and_special_equipments', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('weapons_and_special_equipments', sa.Column('pr_73', sa.SmallInteger(), nullable=True))
    op.add_column('weapons_and_special_equipments', sa.Column('car_dvrs', sa.SmallInteger(), nullable=True))
    op.drop_constraint('weapons_and_special_equipments_id_sm_key', 'weapons_and_special_equipments', type_='unique')
    op.drop_column('weapons_and_special_equipments', 'PR73')
    op.drop_column('weapons_and_special_equipments', 'car_DVRs')
    op.drop_column('weapons_and_special_equipments', 'id_sm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapons_and_special_equipments', sa.Column('id_sm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('weapons_and_special_equipments', sa.Column('car_DVRs', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('weapons_and_special_equipments', sa.Column('PR73', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('weapons_and_special_equipments_id_sm_key', 'weapons_and_special_equipments', ['id_sm'])
    op.drop_column('weapons_and_special_equipments', 'car_dvrs')
    op.drop_column('weapons_and_special_equipments', 'pr_73')
    op.drop_column('weapons_and_special_equipments', 'sm_state')
    # ### end Alembic commands ###
