"""refactored tables

Revision ID: b4133d18848b
Revises: e86ef2a7eb43
Create Date: 2025-02-10 09:36:35.588120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4133d18848b'
down_revision: Union[str, None] = 'e86ef2a7eb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('warning_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('customer_id_sm', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('contract_number', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'contracts', 'customers', ['customer_id_sm'], ['id_sm'], ondelete='NO ACTION')
    op.drop_column('filials', 'longitude')
    op.drop_column('filials', 'latitude')
    op.drop_constraint('income_customer_id_sm_fkey', 'income', type_='foreignkey')
    op.drop_constraint('income_object_id_sm_fkey', 'income', type_='foreignkey')
    op.drop_column('income', 'customer_id_sm')
    op.drop_column('income', 'object_id_sm')
    op.add_column('objects', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'category')
    op.add_column('income', sa.Column('object_id_sm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('income', sa.Column('customer_id_sm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('income_object_id_sm_fkey', 'income', 'objects', ['object_id_sm'], ['id_sm'])
    op.create_foreign_key('income_customer_id_sm_fkey', 'income', 'customers', ['customer_id_sm'], ['id_sm'])
    op.add_column('filials', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('filials', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'contract_number')
    op.drop_column('contracts', 'type')
    op.drop_column('contracts', 'customer_id_sm')
    op.drop_column('contracts', 'end_date')
    op.drop_column('contracts', 'warning_date')
    op.drop_column('contracts', 'start_date')
    # ### end Alembic commands ###
