"""added cummunication facilities

Revision ID: b4713c1663a6
Revises: ff98e4493f3f
Create Date: 2025-02-24 12:02:25.525066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4713c1663a6'
down_revision: Union[str, None] = 'ff98e4493f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_facilities', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('communication_facilities', sa.Column('wearable_radios_quantity', sa.SmallInteger(), nullable=True))
    op.add_column('communication_facilities', sa.Column('сar_radios_quantity', sa.SmallInteger(), nullable=True))
    op.add_column('communication_facilities', sa.Column('stationary_radios_quantity', sa.SmallInteger(), nullable=True))
    op.drop_constraint('communication_facilities_id_sm_key', 'communication_facilities', type_='unique')
    op.drop_column('communication_facilities', 'id_sm')
    op.drop_column('communication_facilities', 'stationary_radios_quant')
    op.drop_column('communication_facilities', 'wearable_radios_quant')
    op.drop_column('communication_facilities', 'сar_radios_quant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_facilities', sa.Column('сar_radios_quant', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('communication_facilities', sa.Column('wearable_radios_quant', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('communication_facilities', sa.Column('stationary_radios_quant', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('communication_facilities', sa.Column('id_sm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('communication_facilities_id_sm_key', 'communication_facilities', ['id_sm'])
    op.drop_column('communication_facilities', 'stationary_radios_quantity')
    op.drop_column('communication_facilities', 'сar_radios_quantity')
    op.drop_column('communication_facilities', 'wearable_radios_quantity')
    op.drop_column('communication_facilities', 'sm_state')
    # ### end Alembic commands ###
