"""increase sql_error field

Revision ID: be0a141266c2
Revises: 02f4eda0821f
Create Date: 2025-02-10 12:30:07.929970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0a141266c2'
down_revision: Union[str, None] = '02f4eda0821f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sql_errors', 'sql',
               existing_type=sa.VARCHAR(length=511),
               type_=sa.String(length=2047),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sql_errors', 'sql',
               existing_type=sa.String(length=2047),
               type_=sa.VARCHAR(length=511),
               existing_nullable=False)
    # ### end Alembic commands ###
