"""Created new tables

Revision ID: c187f40f3c3b
Revises: cdd941c478f8
Create Date: 2025-02-17 10:22:23.935861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c187f40f3c3b'
down_revision: Union[str, None] = 'cdd941c478f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_TRU', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('legal_claims', sa.Column('sm_state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_claims', 'sm_state')
    op.drop_column('contract_TRU', 'sm_state')
    # ### end Alembic commands ###
