"""shifts made id_sm non-unique

Revision ID: cdd941c478f8
Revises: a3d19138324b
Create Date: 2025-02-11 15:00:50.307317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd941c478f8'
down_revision: Union[str, None] = 'a3d19138324b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'id_sm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('shifts_id_sm_key', 'shifts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('shifts_id_sm_key', 'shifts', ['id_sm'])
    op.alter_column('shifts', 'id_sm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
