"""fixed typo

Revision ID: ce97b91dd68c
Revises: e089ed0e9298
Create Date: 2025-01-30 12:43:39.450420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce97b91dd68c'
down_revision: Union[str, None] = 'e089ed0e9298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_guards', sa.Column('gender', sa.String(length=255), nullable=True))
    op.drop_column('security_guards', 'jender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_guards', sa.Column('jender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('security_guards', 'gender')
    # ### end Alembic commands ###
