"""Alter table objects

Revision ID: cf280e33ce4a
Revises: 0acd355ceddf
Create Date: 2025-01-24 14:14:26.991858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf280e33ce4a'
down_revision: Union[str, None] = '0acd355ceddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('contract_number', sa.Text(), nullable=True))
    op.drop_column('objects', 'dogovor_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('dogovor_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('objects', 'contract_number')
    # ### end Alembic commands ###
