"""Initial

Revision ID: d1ecd499f2eb
Revises: 
Create Date: 2025-01-29 11:00:28.987125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ecd499f2eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('filials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bin', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=False),
    sa.Column('customer_id_sm', sa.Integer(), nullable=False),
    sa.Column('dogovor_id_sm', sa.Integer(), nullable=True),
    sa.Column('contract', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('contract_number', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dogovor_id_sm'], ['contract.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('filial_id_sm', sa.Integer(), nullable=False),
    sa.Column('customer_id_sm', sa.Integer(), nullable=False),
    sa.Column('object_id_sm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('shift_mode', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id_sm'], ['customers.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filial_id_sm'], ['filials.id_sm'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id_sm'], ['objects.id_sm'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('objects')
    op.drop_table('customers')
    op.drop_table('filials')
    op.drop_table('contract')
    # ### end Alembic commands ###
