"""create table

Revision ID: dcb95f6ac1f7
Revises: b7e489ab325f
Create Date: 2025-02-17 12:41:33.332306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb95f6ac1f7'
down_revision: Union[str, None] = 'b7e489ab325f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_tru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sm_state', sa.String(length=255), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sm')
    )
    op.add_column('legal_claims', sa.Column('contract_tru_id_sm', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'legal_claims', 'contract_tru', ['contract_tru_id_sm'], ['id_sm'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'legal_claims', type_='foreignkey')
    op.drop_column('legal_claims', 'contract_tru_id_sm')
    op.drop_table('contract_tru')
    # ### end Alembic commands ###
