"""removed filial_id in customers

Revision ID: e089ed0e9298
Revises: 59af41a69f8b
Create Date: 2025-01-30 10:03:18.022552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e089ed0e9298'
down_revision: Union[str, None] = '59af41a69f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_filial_id_sm_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'filial_id_sm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('filial_id_sm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('customers_filial_id_sm_fkey', 'customers', 'filials', ['filial_id_sm'], ['id_sm'], ondelete='CASCADE')
    # ### end Alembic commands ###
