"""initial

Revision ID: e81dd58beccf
Revises: 
Create Date: 2024-12-30 11:28:26.749153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81dd58beccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OS_NMA',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_filial', sa.Integer(), nullable=True),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('name_short', sa.Text(), nullable=True),
    sa.Column('code1C', sa.Integer(), nullable=True),
    sa.Column('inventory_number', sa.Integer(), nullable=True),
    sa.Column('OS_groups', sa.Text(), nullable=True),
    sa.Column('name_of_reg_type', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('battery_life', sa.Date(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('cars',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_cars', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('state_number', sa.Text(), nullable=True),
    sa.Column('engine_displacement', sa.Text(), nullable=True),
    sa.Column('fuel', sa.Text(), nullable=True),
    sa.Column('year_of_production', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('card_of_refueling', sa.Integer(), nullable=True),
    sa.Column('battery_name', sa.Text(), nullable=True),
    sa.Column('battery_life_years', sa.Integer(), nullable=True),
    sa.Column('battery_life', sa.Date(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('communication_means',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('wearable_radios', sa.Integer(), nullable=True),
    sa.Column('car_radios', sa.Integer(), nullable=True),
    sa.Column('stationary_radios', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('customers',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.Text(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('s_bin', sa.Text(), nullable=True),
    sa.Column('d_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('drivers',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('is_sb_drivers', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('surname', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('employee_photo', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('events',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('data_to_police', sa.Text(), nullable=True),
    sa.Column('case_to_police', sa.SmallInteger(), nullable=True),
    sa.Column('act_to_security_council', sa.SmallInteger(), nullable=True),
    sa.Column('customer_employees', sa.SmallInteger(), nullable=True),
    sa.Column('kmg_security_employees', sa.SmallInteger(), nullable=True),
    sa.Column('contractor_employees', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('commit_date', sa.Date(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('amount_of_damage', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('kmgs_ltd', sa.Text(), nullable=True),
    sa.Column('third_party', sa.Text(), nullable=True),
    sa.Column('disciplinary', sa.Text(), nullable=True),
    sa.Column('kui', sa.Text(), nullable=True),
    sa.Column('erdr', sa.Text(), nullable=True),
    sa.Column('sb', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('filial',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('s_name_filial', sa.Text(), nullable=True),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('d_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('filial_director',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_director_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('surname', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('employee_photo', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('filial_ld',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('s_filial', sa.Text(), nullable=True),
    sa.Column('i_count', sa.Integer(), nullable=True),
    sa.Column('i_max', sa.Integer(), nullable=True),
    sa.Column('d_first', sa.DateTime(), nullable=True),
    sa.Column('d_new', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('incidents',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.Text(), nullable=True),
    sa.Column('case_to_police', sa.SmallInteger(), nullable=True),
    sa.Column('act_to_security_council', sa.SmallInteger(), nullable=True),
    sa.Column('customers_employees', sa.SmallInteger(), nullable=True),
    sa.Column('kmg_security_employees', sa.SmallInteger(), nullable=True),
    sa.Column('contractor_employees', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('commit_date', sa.Date(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('amount_of_damage', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('kmgs_ltd', sa.Text(), nullable=True),
    sa.Column('third_party', sa.Text(), nullable=True),
    sa.Column('disciplinary', sa.Text(), nullable=True),
    sa.Column('kui', sa.Text(), nullable=True),
    sa.Column('erdr', sa.Text(), nullable=True),
    sa.Column('sb', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('i_id', 'id_sb_object_filial')
    )
    op.create_table('income',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_dogovor', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Text(), nullable=True),
    sa.Column('contract_amount', sa.Double(), nullable=True),
    sa.Column('add_aggr_amount', sa.Double(), nullable=True),
    sa.Column('amount_avr', sa.Double(), nullable=True),
    sa.Column('payment_date_avr', sa.Date(), nullable=True),
    sa.Column('actual_amount', sa.Double(), nullable=True),
    sa.Column('payment_date_actual', sa.Date(), nullable=True),
    sa.Column('deviation_amount', sa.Double(), nullable=True),
    sa.Column('deviation_from_avr', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('inventory',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_tmz', sa.Integer(), nullable=True),
    sa.Column('id_sb_filial', sa.Integer(), nullable=True),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('name_short', sa.Text(), nullable=True),
    sa.Column('product_group', sa.Text(), nullable=True),
    sa.Column('warehouse', sa.Text(), nullable=True),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('post', sa.Text(), nullable=True),
    sa.Column('remainder', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('issuance_of_OS_TMZ',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_filial', sa.Integer(), nullable=True),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('name_short', sa.Text(), nullable=True),
    sa.Column('product_group', sa.Text(), nullable=True),
    sa.Column('warehouse', sa.Text(), nullable=True),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('post', sa.Text(), nullable=True),
    sa.Column('remainder', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('journal',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('log_of_acceptance', sa.SmallInteger(), nullable=True),
    sa.Column('finery_journal', sa.SmallInteger(), nullable=True),
    sa.Column('log_if_incoming', sa.SmallInteger(), nullable=True),
    sa.Column('import_export_logbook', sa.SmallInteger(), nullable=True),
    sa.Column('acceptance_log_for_premises_delivery', sa.SmallInteger(), nullable=True),
    sa.Column('visitor_log', sa.SmallInteger(), nullable=True),
    sa.Column('vehicle_registration_log', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('mob_groups',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('mg_name', sa.Text(), nullable=True),
    sa.Column('work_mode', sa.Text(), nullable=True),
    sa.Column('shift_mode', sa.Text(), nullable=True),
    sa.Column('linear_part', sa.Text(), nullable=True),
    sa.Column('length_from', sa.Text(), nullable=True),
    sa.Column('length_to', sa.Text(), nullable=True),
    sa.Column('d_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('mobile_group_composition',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_guard', sa.Integer(), nullable=True),
    sa.Column('id_driver', sa.Integer(), nullable=True),
    sa.Column('id_car', sa.Integer(), nullable=True),
    sa.Column('id_sb_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('subdivision', sa.Text(), nullable=True),
    sa.Column('shift_mode', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('motor_transport',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('motor_transport', sa.Integer(), nullable=True),
    sa.Column('additional_sites', sa.Integer(), nullable=True),
    sa.Column('gps', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('objects',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('dogovor', sa.Text(), nullable=True),
    sa.Column('sb_id_dogovor', sa.Integer(), nullable=True),
    sa.Column('dogovor_date', sa.Date(), nullable=True),
    sa.Column('dogovor_num', sa.Text(), nullable=True),
    sa.Column('object_type', sa.Text(), nullable=True),
    sa.Column('d_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('offenses',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('offense_type', sa.Text(), nullable=True),
    sa.Column('data_to_police', sa.Text(), nullable=True),
    sa.Column('case_to_police', sa.SmallInteger(), nullable=True),
    sa.Column('act_to_security_council', sa.SmallInteger(), nullable=True),
    sa.Column('customer_employees', sa.SmallInteger(), nullable=True),
    sa.Column('kmg_security_employees', sa.SmallInteger(), nullable=True),
    sa.Column('contractor_employees', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('commit_date', sa.Date(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('amount_of_damage', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('kmgs_ltd', sa.Text(), nullable=True),
    sa.Column('third_party', sa.Text(), nullable=True),
    sa.Column('disciplinary', sa.Text(), nullable=True),
    sa.Column('kui', sa.Text(), nullable=True),
    sa.Column('erdr', sa.Text(), nullable=True),
    sa.Column('sb', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('posts',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('post_name', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Text(), nullable=True),
    sa.Column('shift_mode', sa.Text(), nullable=True),
    sa.Column('d_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('providing_workwear',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('motor_transport', sa.Integer(), nullable=True),
    sa.Column('gps', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('requirement_request',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('nomination', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('code', sa.Double(), nullable=True),
    sa.Column('feature', sa.Text(), nullable=True),
    sa.Column('to_whom', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('route_sheet',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('route_number', sa.Text(), nullable=True),
    sa.Column('id_sb_mashina', sa.Integer(), nullable=True),
    sa.Column('base_object_name', sa.Text(), nullable=True),
    sa.Column('protected_area', sa.Text(), nullable=True),
    sa.Column('length_of_perimeter_of_area', sa.Text(), nullable=True),
    sa.Column('area_of_sector', sa.Text(), nullable=True),
    sa.Column('senior_driver_guard', sa.Text(), nullable=True),
    sa.Column('driver_guard_1', sa.Text(), nullable=True),
    sa.Column('driver_guard_2', sa.Text(), nullable=True),
    sa.Column('bypass_post_guard', sa.Text(), nullable=True),
    sa.Column('working_time_from', sa.DateTime(), nullable=True),
    sa.Column('working_time_to', sa.DateTime(), nullable=True),
    sa.Column('route_task_prepared', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('secutiry_guard',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_guard', sa.Integer(), nullable=True),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('employee_photo', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('shift_schedule',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('id_sb_ohranniki', sa.Integer(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Text(), nullable=True),
    sa.Column('shift_type', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('special_equipment',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_spec_sredstva', sa.Integer(), nullable=True),
    sa.Column('nomination', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('staff',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('staffing_level', sa.Integer(), nullable=True),
    sa.Column('payroll', sa.Integer(), nullable=True),
    sa.Column('actual_number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('staff_turnover',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('staffing_level', sa.Integer(), nullable=True),
    sa.Column('payroll', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Integer(), nullable=True),
    sa.Column('fired', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('training_and_medical_services',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('annual_retraining_of_security_guards', sa.Integer(), nullable=True),
    sa.Column('anti_terrorism_training', sa.Integer(), nullable=True),
    sa.Column('fire_technical_minimum', sa.Integer(), nullable=True),
    sa.Column('annual_medical_examination', sa.Integer(), nullable=True),
    sa.Column('pre_shift_medical_examination', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('triggering',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_object', sa.Integer(), nullable=True),
    sa.Column('name_customer', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('departure_mg', sa.Boolean(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('description_of_additional_check', sa.Text(), nullable=True),
    sa.Column('response_time', sa.Time(), nullable=True),
    sa.Column('mg_moment_of_actuation', sa.Text(), nullable=True),
    sa.Column('trigger_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('weapons',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_oruzhie', sa.Integer(), nullable=True),
    sa.Column('weapon', sa.Text(), nullable=True),
    sa.Column('type_of_weapon', sa.Text(), nullable=True),
    sa.Column('weapon_number', sa.Integer(), nullable=True),
    sa.Column('ammunition', sa.Integer(), nullable=True),
    sa.Column('weapons', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    op.create_table('weapons_and_special_quipment',
    sa.Column('i_id', sa.Integer(), nullable=False),
    sa.Column('id_sb_object_filial', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_zakazchik', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_mob_group', sa.Integer(), nullable=True),
    sa.Column('id_sb_object_post', sa.Integer(), nullable=True),
    sa.Column('firearms', sa.Integer(), nullable=True),
    sa.Column('handcuffs', sa.Integer(), nullable=True),
    sa.Column('pr_73', sa.Integer(), nullable=True),
    sa.Column('regulatory', sa.Integer(), nullable=True),
    sa.Column('electric_lantern', sa.Integer(), nullable=True),
    sa.Column('headlight_finder', sa.Integer(), nullable=True),
    sa.Column('inspection_mirror', sa.Integer(), nullable=True),
    sa.Column('metal_detectors', sa.Integer(), nullable=True),
    sa.Column('binoculars', sa.Integer(), nullable=True),
    sa.Column('safe', sa.Integer(), nullable=True),
    sa.Column('wearable_video_recorders', sa.Integer(), nullable=True),
    sa.Column('car_dvr', sa.Integer(), nullable=True),
    sa.Column('cell_phones', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('i_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapons_and_special_quipment')
    op.drop_table('weapons')
    op.drop_table('triggering')
    op.drop_table('training_and_medical_services')
    op.drop_table('staff_turnover')
    op.drop_table('staff')
    op.drop_table('special_equipment')
    op.drop_table('shift_schedule')
    op.drop_table('secutiry_guard')
    op.drop_table('route_sheet')
    op.drop_table('requirement_request')
    op.drop_table('providing_workwear')
    op.drop_table('posts')
    op.drop_table('offenses')
    op.drop_table('objects')
    op.drop_table('motor_transport')
    op.drop_table('mobile_group_composition')
    op.drop_table('mob_groups')
    op.drop_table('journal')
    op.drop_table('issuance_of_OS_TMZ')
    op.drop_table('inventory')
    op.drop_table('income')
    op.drop_table('incidents')
    op.drop_table('filial_ld')
    op.drop_table('filial_director')
    op.drop_table('filial')
    op.drop_table('events')
    op.drop_table('drivers')
    op.drop_table('customers')
    op.drop_table('communication_means')
    op.drop_table('cars')
    op.drop_table('OS_NMA')
    # ### end Alembic commands ###
