"""Refactored journals

Revision ID: ff98e4493f3f
Revises: b8c7abe04e4f
Create Date: 2025-02-24 11:13:06.568527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff98e4493f3f'
down_revision: Union[str, None] = 'b8c7abe04e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('sm_state', sa.String(length=255), nullable=True))
    op.add_column('journals', sa.Column('journal_transfer_of_weapons_and_ammunition', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_finery', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_aboard', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_list_of_way', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_information_and_recording', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_transfers_of_inventory_items', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_acceptance_log_for_premises_delivery', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_visitors', sa.Boolean(), nullable=True))
    op.add_column('journals', sa.Column('journal_vehicle_registration', sa.Boolean(), nullable=True))
    op.drop_constraint('journals_id_sm_key', 'journals', type_='unique')
    op.drop_column('journals', 'id_sm')
    op.drop_column('journals', 'acceptance_log_for_premises_delivery')
    op.drop_column('journals', 'vehicle_registration_log')
    op.drop_column('journals', 'visitor_log')
    op.drop_column('journals', 'log_of_accept_and_transf_of_weapon_and_ammunition')
    op.drop_column('journals', 'log_of_inc_info_and_recor_of_activation_of_tech_sec_means')
    op.drop_column('journals', 'finery_journal')
    op.drop_column('journals', 'import_export_log_and_contrib_removals_of_inventory_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('import_export_log_and_contrib_removals_of_inventory_items', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('finery_journal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('log_of_inc_info_and_recor_of_activation_of_tech_sec_means', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('log_of_accept_and_transf_of_weapon_and_ammunition', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('visitor_log', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('vehicle_registration_log', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('acceptance_log_for_premises_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('id_sm', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('journals_id_sm_key', 'journals', ['id_sm'])
    op.drop_column('journals', 'journal_vehicle_registration')
    op.drop_column('journals', 'journal_visitors')
    op.drop_column('journals', 'journal_acceptance_log_for_premises_delivery')
    op.drop_column('journals', 'journal_transfers_of_inventory_items')
    op.drop_column('journals', 'journal_information_and_recording')
    op.drop_column('journals', 'journal_list_of_way')
    op.drop_column('journals', 'journal_aboard')
    op.drop_column('journals', 'journal_finery')
    op.drop_column('journals', 'journal_transfer_of_weapons_and_ammunition')
    op.drop_column('journals', 'sm_state')
    # ### end Alembic commands ###
